[toolchain]
channel = "1.87"
components = [
  "rustfmt",
  "rustc",
  "rust-src",
  "rust-analyzer",
  "cargo",
  "clippy",
]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "aarch64-pc-windows-msvc",
]
profile = "minimal"
